[turn_servers]
turn1 ansible_host=188.137.229.86 ansible_user=root ansible_ssh_private_key_file=~/.ssh/external-server

[turn_servers:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'